---
title: Prof. Vinicius Ramos, Ph.D.
timezone: America/Sao_Paulo
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: true
    permalink: "/:collection/:path/"
  talks:
    title: Talks
    output: true
    permalink: "/:collection/:path/"
  teaching:
    title: Teaching
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: teaching
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: publications
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: talks
  values:
    layout: talk
    author_profile: true
    share: true
locale: en-US
title_separator: "-"
name: Vinicius Ramos
description: Ph.D. in Systems and Computer Engineering at the Federal University of
  Rio de Janeiro (Brazil) jointly with the Eindhoven University of Technology (Holland).
  Associate Professor in the Sciences, Technologies, and Health Center of the Federal
  University of Santa Catarina (Brazil). His research interests include the use of
  intelligent systems in education, learning analytics, social networks analysis and
  education in computer science.
url: https://viniciusramos.pro.br
baseurl: ''
repository: professorviniciusramos.github.io
teaser: photo_vinicius_820x820.png
breadcrumbs: false
words_per_minute: 160
future: true
read_more: disabled
talkmap_link: false
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google-universal
  google:
    tracking_id: 
author:
  name: Vinicius Ramos, Ph.D.
  avatar: photo_vinicius_820x820.png
  bio: Associate Professor at Federal University of Santa Catarina (UFSC), member
    of the Lab. Sistemas de Conhecimento (LSC), and BOTAFOGO F.R. supporter
  location: 
  employer: UFSC
  pubmed: 
  googlescholar: https://scholar.google.com/citations?user=VOvnnI4AAAAJ&hl=en
  email: v.ramos <at> ufsc <dot> br
  researchgate: https://www.researchgate.net/profile/Vinicius_Ramos6
  uri: https://viniciusramos.pro.br
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: professorviniciusramos
  skype: viniciusfcramos
  google_plus: 
  keybase: 
  instagram: 
  impactstory: 
  lastfm: 
  linkedin: 
  orcid: https://orcid.org/0000-0002-8319-743X
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: 
  vine: 
  weibo: 
  xing: 
  youtube: 
  wikipedia: 
include:
- ".htaccess"
- _pages
- files
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- assets/js/_main.js
- assets/js/plugins
- assets/js/vendor
- config
- gulpfile.js
- log
- node_modules
- package.json
- tmp
- vendor
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
